# Generated by Django 3.2.4 on 2021-06-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0002_myuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
